// Auto-generated from Overtone UGen metadata
// https://github.com/overtone/overtone/tree/master/src/overtone/sc/machinery/ugen/metadata
// Do not edit manually.

import {Rate} from './ugen';
import {registerUGen} from './registry';

registerUGen({name: 'A2K', rates: [Rate.Control], defaults: [['in', 0]]});
registerUGen({name: 'AllpassC', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['maxDelayTime', 0.2], ['delayTime', 0.2], ['decayTime', 1]]});
registerUGen({name: 'AllpassL', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['maxDelayTime', 0.2], ['delayTime', 0.2], ['decayTime', 1]]});
registerUGen({name: 'AllpassN', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['maxDelayTime', 0.2], ['delayTime', 0.2], ['decayTime', 1]]});
registerUGen({name: 'AmpComp', rates: [Rate.Scalar, Rate.Audio, Rate.Control], defaults: [['freq', 261.6256], ['root', 261.6256], ['exp', 0.3333]]});
registerUGen({name: 'AmpCompA', rates: [Rate.Scalar, Rate.Audio, Rate.Control], defaults: [['freq', 1000], ['root', 0], ['minAmp', 0.32], ['rootAmp', 1]]});
registerUGen({name: 'Amplitude', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['attackTime', 0.01], ['releaseTime', 0.01]]});
registerUGen({name: 'APF', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['freq', 440], ['radius', 0.8]]});
registerUGen({name: 'Balance2', rates: [Rate.Audio], defaults: [['left', undefined], ['right', undefined], ['pos', 0], ['level', 1]], numOutputs: 2});
registerUGen({name: 'Ball', rates: [Rate.Audio], defaults: [['in', 0], ['g', 1], ['damp', 0], ['friction', 0.01]]});
registerUGen({name: 'BAllPass', rates: [Rate.Audio], defaults: [['in', undefined], ['freq', 1200], ['rq', 1]]});
registerUGen({name: 'BBandPass', rates: [Rate.Audio], defaults: [['in', undefined], ['freq', 1200], ['bw', 1]]});
registerUGen({name: 'BBandStop', rates: [Rate.Audio], defaults: [['in', undefined], ['freq', 1200], ['bw', 1]]});
registerUGen({name: 'BeatTrack', rates: [Rate.Control], defaults: [['chain', undefined], ['lock', 0]], numOutputs: 4});
registerUGen({name: 'BeatTrack2', rates: [Rate.Control], defaults: [['busindex', undefined], ['numfeatures', undefined], ['windowsize', 2], ['phaseaccuracy', 0.02], ['lock', 0], ['weightingscheme', -2.1]], numOutputs: 6});
registerUGen({name: 'BHiPass', rates: [Rate.Audio], defaults: [['in', undefined], ['freq', 1200], ['rq', 1]]});
registerUGen({name: 'BHiShelf', rates: [Rate.Audio], defaults: [['in', undefined], ['freq', 1200], ['rs', 1], ['db', 0]]});
registerUGen({name: 'BiPanB2', rates: [Rate.Audio, Rate.Control], defaults: [['inA', undefined], ['inB', undefined], ['azimuth', undefined], ['gain', 1]], numOutputs: 3});
registerUGen({name: 'Blip', rates: [Rate.Audio], defaults: [['freq', 440], ['numharm', 200]]});
registerUGen({name: 'BLowPass', rates: [Rate.Audio], defaults: [['in', undefined], ['freq', 1200], ['rq', 1]]});
registerUGen({name: 'BLowShelf', rates: [Rate.Audio], defaults: [['in', undefined], ['freq', 1200], ['rs', 1], ['db', 0]]});
registerUGen({name: 'BPeakEQ', rates: [Rate.Audio], defaults: [['in', undefined], ['freq', 1200], ['rq', 1], ['db', 0]]});
registerUGen({name: 'BPF', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['freq', 440], ['rq', 1]]});
registerUGen({name: 'BPZ2', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0]]});
registerUGen({name: 'BRF', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['freq', 440], ['rq', 1]]});
registerUGen({name: 'BrownNoise', rates: [Rate.Audio, Rate.Control], defaults: []});
registerUGen({name: 'BRZ2', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0]]});
registerUGen({name: 'BufAllpassC', rates: [Rate.Audio], defaults: [['buf', 0], ['in', 0], ['delayTime', 0.2], ['decayTime', 1]]});
registerUGen({name: 'BufAllpassL', rates: [Rate.Audio], defaults: [['buf', 0], ['in', 0], ['delayTime', 0.2], ['decayTime', 1]]});
registerUGen({name: 'BufAllpassN', rates: [Rate.Audio], defaults: [['buf', 0], ['in', 0], ['delayTime', 0.2], ['decayTime', 1]]});
registerUGen({name: 'BufChannels', rates: [Rate.Control, Rate.Scalar], defaults: [['buf', 0]]});
registerUGen({name: 'BufCombC', rates: [Rate.Audio], defaults: [['buf', 0], ['in', 0], ['delayTime', 0.2], ['decayTime', 1]]});
registerUGen({name: 'BufCombL', rates: [Rate.Audio], defaults: [['buf', 0], ['in', 0], ['delayTime', 0.2], ['decayTime', 1]]});
registerUGen({name: 'BufCombN', rates: [Rate.Audio], defaults: [['buf', 0], ['in', 0], ['delayTime', 0.2], ['decayTime', 1]]});
registerUGen({name: 'BufDelayC', rates: [Rate.Audio, Rate.Control], defaults: [['buf', 0], ['in', 0], ['delayTime', 0.2]]});
registerUGen({name: 'BufDelayL', rates: [Rate.Audio, Rate.Control], defaults: [['buf', 0], ['in', 0], ['delayTime', 0.2]]});
registerUGen({name: 'BufDelayN', rates: [Rate.Audio, Rate.Control], defaults: [['buf', 0], ['in', 0], ['delayTime', 0.2]]});
registerUGen({name: 'BufDur', rates: [Rate.Control, Rate.Scalar], defaults: [['buf', 0]]});
registerUGen({name: 'BufFrames', rates: [Rate.Control, Rate.Scalar], defaults: [['buf', 0]]});
registerUGen({name: 'BufRateScale', rates: [Rate.Control, Rate.Scalar], defaults: [['buf', 0]]});
registerUGen({name: 'BufRd', rates: [Rate.Audio, Rate.Control], defaults: [['numChannels', 1], ['bufnum', 0], ['phase', 0], ['loop', 1], ['interpolation', 2]]});
registerUGen({name: 'BufSampleRate', rates: [Rate.Control, Rate.Scalar], defaults: [['buf', 0]]});
registerUGen({name: 'BufSamples', rates: [Rate.Control, Rate.Scalar], defaults: [['buf', 0]]});
registerUGen({name: 'BufWr', rates: [Rate.Audio, Rate.Control], defaults: [['inputArray', undefined], ['bufnum', 0], ['phase', 0], ['loop', 1]], numOutputs: 0});
registerUGen({name: 'CheckBadValues', rates: [Rate.Control, Rate.Scalar], defaults: [['in', undefined], ['id', 0], ['post', 2]]});
registerUGen({name: 'ClearBuf', rates: [Rate.Scalar], defaults: [['buf', undefined]], numOutputs: 0});
registerUGen({name: 'Clip', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['lo', 0], ['hi', 1]]});
registerUGen({name: 'ClipNoise', rates: [Rate.Audio], defaults: []});
registerUGen({name: 'CoinGate', rates: [Rate.Control, Rate.Scalar], defaults: [['prob', undefined], ['trig', undefined]]});
registerUGen({name: 'CombC', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['maxDelayTime', 0.2], ['delayTime', 0.2], ['decayTime', 1]]});
registerUGen({name: 'CombL', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['maxDelayTime', 0.2], ['delayTime', 0.2], ['decayTime', 1]]});
registerUGen({name: 'CombN', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['maxDelayTime', 0.2], ['delayTime', 0.2], ['decayTime', 1]]});
registerUGen({name: 'Compander', rates: [Rate.Audio], defaults: [['in', 0], ['control', 0], ['thresh', 0.5], ['slopeBelow', 1], ['slopeAbove', 1], ['clampTime', 0.01], ['relaxTime', 0.1]]});
registerUGen({name: 'ControlDur', rates: [Rate.Scalar], defaults: []});
registerUGen({name: 'ControlRate', rates: [Rate.Scalar], defaults: []});
registerUGen({name: 'Convolution', rates: [Rate.Audio], defaults: [['in', undefined], ['kernel', undefined], ['framesize', 512]]});
registerUGen({name: 'Convolution2', rates: [Rate.Audio], defaults: [['in', undefined], ['kernel', undefined], ['trigger', undefined], ['framesize', 512]]});
registerUGen({name: 'Convolution2L', rates: [Rate.Audio], defaults: [['in', undefined], ['kernel', undefined], ['trigger', undefined], ['framesize', 512], ['crossfade', 1]]});
registerUGen({name: 'Convolution3', rates: [Rate.Audio, Rate.Control], defaults: [['in', undefined], ['kernel', undefined], ['trigger', 0], ['framesize', 512]]});
registerUGen({name: 'COsc', rates: [Rate.Audio, Rate.Control], defaults: [['bufnum', undefined], ['freq', 440], ['beats', 0.5]]});
registerUGen({name: 'Crackle', rates: [Rate.Audio, Rate.Control], defaults: [['chaosParam', 1.5]]});
registerUGen({name: 'CuspL', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['a', 1], ['b', 1.9], ['xi', 0]]});
registerUGen({name: 'CuspN', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['a', 1], ['b', 1.9], ['xi', 0]]});
registerUGen({name: 'Dbrown', rates: [], defaults: [['length', undefined], ['lo', 0], ['hi', 1], ['step', 0.01]]});
registerUGen({name: 'Dbufrd', rates: [], defaults: [['bufnum', 0], ['phase', 0], ['loop', 1]]});
registerUGen({name: 'Dbufwr', rates: [], defaults: [['bufnum', 0], ['phase', 0], ['input', 0], ['loop', 1]]});
registerUGen({name: 'DC', rates: [Rate.Audio, Rate.Control], defaults: [['in', undefined]]});
registerUGen({name: 'Decay', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['decayTime', 1]]});
registerUGen({name: 'Decay2', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['attackTime', 0.01], ['decayTime', 1]]});
registerUGen({name: 'DecodeB2', rates: [Rate.Audio, Rate.Control], defaults: [['numChannels', undefined], ['w', undefined], ['x', undefined], ['y', undefined], ['orientation', 0.5]]});
registerUGen({name: 'DegreeToKey', rates: [Rate.Audio, Rate.Control], defaults: [['bufnum', undefined], ['in', 0], ['octave', 12]]});
registerUGen({name: 'Delay1', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0]]});
registerUGen({name: 'Delay2', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0]]});
registerUGen({name: 'DelayC', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['maxDelayTime', 0.2], ['delayTime', 0.2]]});
registerUGen({name: 'DelayL', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['maxDelayTime', 0.2], ['delayTime', 0.2]]});
registerUGen({name: 'DelayN', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['maxDelayTime', 0.2], ['delayTime', 0.2]]});
registerUGen({name: 'DelTapRd', rates: [Rate.Audio, Rate.Control], defaults: [['buffer', 0], ['phase', 0], ['delay', 0], ['interp', 1]]});
registerUGen({name: 'DelTapWr', rates: [Rate.Audio, Rate.Control], defaults: [['buffer', 0], ['in', 0]]});
registerUGen({name: 'Demand', rates: [Rate.Audio, Rate.Control], defaults: [['trig', undefined], ['reset', 0], ['demandUgens', undefined]]});
registerUGen({name: 'DemandEnvGen', rates: [Rate.Audio, Rate.Control], defaults: [['level', undefined], ['dur', undefined], ['shape', 1], ['curve', 0], ['gate', 1], ['reset', 1], ['levelScale', 1], ['levelBias', 0], ['timeScale', 1], ['action', 0]]});
registerUGen({name: 'DetectIndex', rates: [Rate.Control, Rate.Scalar], defaults: [['bufnum', undefined], ['in', 0]]});
registerUGen({name: 'DetectSilence', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['amp', 0.0001], ['time', 0.1], ['action', 0]]});
registerUGen({name: 'Dgeom', rates: [], defaults: [['length', undefined], ['start', 1], ['grow', 2]]});
registerUGen({name: 'Dibrown', rates: [], defaults: [['length', undefined], ['lo', 0], ['hi', 1], ['step', 0.01]]});
registerUGen({name: 'DiskIn', rates: [Rate.Audio], defaults: [['numChannels', undefined], ['bufnum', undefined], ['loop', 0]]});
registerUGen({name: 'DiskOut', rates: [Rate.Audio], defaults: [['bufnum', undefined], ['channelsArray', undefined]], numOutputs: 0});
registerUGen({name: 'Diwhite', rates: [], defaults: [['length', undefined], ['lo', 0], ['hi', 1]]});
registerUGen({name: 'Donce', rates: [], defaults: [['in', undefined]]});
registerUGen({name: 'Done', rates: [Rate.Control], defaults: [['src', undefined]]});
registerUGen({name: 'Dpoll', rates: [], defaults: [['in', undefined], ['trigId', -1], ['label', undefined], ['run', 1]]});
registerUGen({name: 'Drand', rates: [], defaults: [['list', undefined], ['numRepeats', 1]]});
registerUGen({name: 'Dseq', rates: [], defaults: [['list', undefined], ['numRepeats', 1]]});
registerUGen({name: 'Dser', rates: [], defaults: [['list', undefined], ['count', 1]]});
registerUGen({name: 'Dseries', rates: [], defaults: [['length', undefined], ['start', 1], ['step', 1]]});
registerUGen({name: 'Dshuf', rates: [], defaults: [['list', undefined], ['numRepeats', 1]]});
registerUGen({name: 'Dstutter', rates: [], defaults: [['numRepeats', undefined], ['in', undefined]]});
registerUGen({name: 'Dswitch', rates: [], defaults: [['list', undefined], ['index', undefined]]});
registerUGen({name: 'Dswitch1', rates: [], defaults: [['list', undefined], ['index', undefined]]});
registerUGen({name: 'Dust', rates: [Rate.Audio, Rate.Control], defaults: [['density', 0]]});
registerUGen({name: 'Dust2', rates: [Rate.Audio, Rate.Control], defaults: [['density', 0]]});
registerUGen({name: 'Duty', rates: [Rate.Audio, Rate.Control], defaults: [['dur', 1], ['reset', 0], ['action', 0], ['level', 1]]});
registerUGen({name: 'Dwhite', rates: [], defaults: [['length', undefined], ['lo', 0], ['hi', 1]]});
registerUGen({name: 'Dxrand', rates: [], defaults: [['list', undefined], ['numRepeats', 1]]});
registerUGen({name: 'EnvGen', rates: [Rate.Audio, Rate.Control], defaults: [['envelope', undefined], ['gate', 1], ['levelScale', 1], ['levelBias', 0], ['timeScale', 1], ['action', 0]]});
registerUGen({name: 'ExpRand', rates: [Rate.Scalar], defaults: [['lo', 0.01], ['hi', 1]]});
registerUGen({name: 'FBSineC', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['im', 1], ['fb', 0.1], ['a', 1.1], ['c', 0.5], ['xi', 0.1], ['yi', 0.1]]});
registerUGen({name: 'FBSineL', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['im', 1], ['fb', 0.1], ['a', 1.1], ['c', 0.5], ['xi', 0.1], ['yi', 0.1]]});
registerUGen({name: 'FBSineN', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['im', 1], ['fb', 0.1], ['a', 1.1], ['c', 0.5], ['xi', 0.1], ['yi', 0.1]]});
registerUGen({name: 'FFT', rates: [Rate.Control], defaults: [['buffer', undefined], ['in', 0], ['hop', 0.5], ['wintype', 0], ['active', 1], ['winsize', 0]]});
registerUGen({name: 'FFTTrigger', rates: [Rate.Control], defaults: [['buffer', undefined], ['hop', 0.5], ['polar', 0]]});
registerUGen({name: 'Fold', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['lo', 0], ['hi', 1]]});
registerUGen({name: 'Formant', rates: [Rate.Audio], defaults: [['fundfreq', 440], ['formfreq', 1760], ['bwfreq', 880]]});
registerUGen({name: 'Formlet', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['freq', 440], ['attackTime', 1], ['decayTime', 1]]});
registerUGen({name: 'FOS', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['a0', 0], ['a1', 0], ['b1', 0]]});
registerUGen({name: 'Free', rates: [Rate.Control], defaults: [['trig', undefined], ['id', undefined]], numOutputs: 0});
registerUGen({name: 'FreeSelf', rates: [Rate.Control], defaults: [['in', undefined]], numOutputs: 0});
registerUGen({name: 'FreeSelfWhenDone', rates: [Rate.Control], defaults: [['src', undefined]], numOutputs: 0});
registerUGen({name: 'FreeVerb', rates: [Rate.Audio], defaults: [['in', undefined], ['mix', 0.33], ['room', 0.5], ['damp', 0.5]]});
registerUGen({name: 'FreeVerb2', rates: [Rate.Audio], defaults: [['in', undefined], ['in2', undefined], ['mix', 0.33], ['room', 0.5], ['damp', 0.5]], numOutputs: 2});
registerUGen({name: 'FreqShift', rates: [Rate.Audio], defaults: [['in', undefined], ['freq', 0], ['phase', 0]]});
registerUGen({name: 'FSinOsc', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 440], ['iphase', 0]]});
registerUGen({name: 'Gate', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['trig', 0]]});
registerUGen({name: 'GbmanL', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['xi', 1.2], ['yi', 2.1]]});
registerUGen({name: 'GbmanN', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['xi', 1.2], ['yi', 2.1]]});
registerUGen({name: 'Gendy1', rates: [Rate.Audio, Rate.Control], defaults: [['ampdist', 1], ['durdist', 1], ['adparam', 1], ['ddparam', 1], ['minfreq', 440], ['maxfreq', 660], ['ampscale', 0.5], ['durscale', 0.5], ['initCps', 12], ['knum', 12]]});
registerUGen({name: 'Gendy2', rates: [Rate.Audio, Rate.Control], defaults: [['ampdist', 1], ['durdist', 1], ['adparam', 1], ['ddparam', 1], ['minfreq', 440], ['maxfreq', 660], ['ampscale', 0.5], ['durscale', 0.5], ['initCps', 12], ['knum', 12], ['a', 1.17], ['c', 0.31]]});
registerUGen({name: 'Gendy3', rates: [Rate.Audio, Rate.Control], defaults: [['ampdist', 1], ['durdist', 1], ['adparam', 1], ['ddparam', 1], ['freq', 440], ['ampscale', 0.5], ['durscale', 0.5], ['initCps', 12], ['knum', 12]]});
registerUGen({name: 'GrainBuf', rates: [Rate.Audio], defaults: [['numChannels', 1], ['trigger', 0], ['dur', 1], ['sndbuf', undefined], ['rate', 1], ['pos', 1], ['interp', 2], ['pan', 0], ['envbufnum', -1], ['maxGrains', 512]]});
registerUGen({name: 'GrainFM', rates: [Rate.Audio], defaults: [['numChannels', 1], ['trigger', 0], ['dur', 1], ['carFreq', 440], ['modFreq', 440], ['index', 1], ['pan', 0], ['envbufnum', -1], ['maxGrains', 512]]});
registerUGen({name: 'GrainIn', rates: [Rate.Audio], defaults: [['numChannels', 1], ['trigger', 0], ['dur', 1], ['in', undefined], ['pan', 0], ['envbufnum', -1], ['maxGrains', 512]]});
registerUGen({name: 'GrainSin', rates: [Rate.Audio], defaults: [['numChannels', 1], ['trigger', 0], ['dur', 1], ['freq', 440], ['pan', 0], ['envbufnum', -1], ['maxGrains', 512]]});
registerUGen({name: 'GrayNoise', rates: [Rate.Audio], defaults: []});
registerUGen({name: 'GVerb', rates: [Rate.Audio], defaults: [['in', undefined], ['roomsize', 10], ['revtime', 3], ['damping', 0.5], ['inputbw', 0.5], ['spread', 15], ['drylevel', 1], ['earlyreflevel', 0.7], ['taillevel', 0.5], ['maxroomsize', 300]], numOutputs: 2});
registerUGen({name: 'Hasher', rates: [Rate.Audio], defaults: [['in', 0]]});
registerUGen({name: 'HenonC', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['a', 1.4], ['b', 0.3], ['x0', 0], ['x1', 0]]});
registerUGen({name: 'HenonL', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['a', 1.4], ['b', 0.3], ['x0', 0], ['x1', 0]]});
registerUGen({name: 'HenonN', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['a', 1.4], ['b', 0.3], ['x0', 0], ['x1', 0]]});
registerUGen({name: 'Hilbert', rates: [Rate.Audio], defaults: [['in', undefined]], numOutputs: 2});
registerUGen({name: 'HPF', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['freq', 440]]});
registerUGen({name: 'HPZ1', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0]]});
registerUGen({name: 'HPZ2', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0]]});
registerUGen({name: 'IEnvGen', rates: [Rate.Audio, Rate.Control], defaults: [['ienvelope', undefined], ['index', undefined]]});
registerUGen({name: 'IFFT', rates: [Rate.Audio, Rate.Control], defaults: [['chain', undefined], ['wintype', 0], ['winsize', 0]]});
registerUGen({name: 'Impulse', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 440], ['phase', 0]]});
registerUGen({name: 'In', rates: [Rate.Audio, Rate.Control], defaults: [['bus', 0], ['numChannels', 1]]});
registerUGen({name: 'Index', rates: [Rate.Control, Rate.Scalar], defaults: [['bufnum', undefined], ['in', 0]]});
registerUGen({name: 'IndexInBetween', rates: [Rate.Control, Rate.Scalar], defaults: [['bufnum', undefined], ['in', 0]]});
registerUGen({name: 'InFeedback', rates: [Rate.Audio], defaults: [['bus', 0], ['numChannels', 1]]});
registerUGen({name: 'InRange', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['lo', 0], ['hi', 1]]});
registerUGen({name: 'InRect', rates: [Rate.Audio, Rate.Control], defaults: [['x', 0], ['y', 0], ['left', undefined], ['top', undefined], ['right', undefined], ['bottom', undefined]]});
registerUGen({name: 'Integrator', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['coef', 1]]});
registerUGen({name: 'InTrig', rates: [Rate.Control], defaults: [['bus', 0], ['numChannels', 1]]});
registerUGen({name: 'IRand', rates: [Rate.Scalar], defaults: [['lo', 0], ['hi', 127]]});
registerUGen({name: 'K2A', rates: [Rate.Audio], defaults: [['in', 0]]});
registerUGen({name: 'KeyState', rates: [Rate.Control], defaults: [['keycode', 0], ['minval', 0], ['maxval', 1], ['lag', 0.2]]});
registerUGen({name: 'KeyTrack', rates: [Rate.Control], defaults: [['chain', undefined], ['keydecay', 2], ['chromaleak', 0.5]]});
registerUGen({name: 'Klang', rates: [Rate.Audio], defaults: [['specs', undefined], ['freqscale', 1], ['freqoffset', 0]]});
registerUGen({name: 'Klank', rates: [Rate.Audio], defaults: [['specs', undefined], ['input', undefined], ['freqscale', 1], ['freqoffset', 0], ['decayscale', 1]]});
registerUGen({name: 'Lag', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['lagTime', 0.1]]});
registerUGen({name: 'Lag2', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['lagTime', 0.1]]});
registerUGen({name: 'Lag2UD', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['lagTimeUp', 0.1], ['lagTimeDown', 0.1]]});
registerUGen({name: 'Lag3', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['lagTime', 0.1]]});
registerUGen({name: 'Lag3UD', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['lagTimeUp', 0.1], ['lagTimeDown', 0.1]]});
registerUGen({name: 'LagIn', rates: [Rate.Control], defaults: [['bus', 0], ['numChannels', 1], ['lag', 0.1]]});
registerUGen({name: 'LagUD', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['lagTimeUp', 0.1], ['lagTimeDown', 0.1]]});
registerUGen({name: 'LastValue', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['diff', 0.01]]});
registerUGen({name: 'Latch', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['trig', 0]]});
registerUGen({name: 'LatoocarfianC', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['a', 1], ['b', 3], ['c', 0.5], ['d', 0.5], ['xi', 0.5], ['yi', 0.5]]});
registerUGen({name: 'LatoocarfianL', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['a', 1], ['b', 3], ['c', 0.5], ['d', 0.5], ['xi', 0.5], ['yi', 0.5]]});
registerUGen({name: 'LatoocarfianN', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['a', 1], ['b', 3], ['c', 0.5], ['d', 0.5], ['xi', 0.5], ['yi', 0.5]]});
registerUGen({name: 'LeakDC', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['coef', 0.995]]});
registerUGen({name: 'LeastChange', rates: [Rate.Audio, Rate.Control], defaults: [['a', 0], ['b', 0]]});
registerUGen({name: 'LFClipNoise', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 500]]});
registerUGen({name: 'LFCub', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 440], ['iphase', 0]]});
registerUGen({name: 'LFDClipNoise', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 500]]});
registerUGen({name: 'LFDNoise0', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 500]]});
registerUGen({name: 'LFDNoise1', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 500]]});
registerUGen({name: 'LFDNoise3', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 500]]});
registerUGen({name: 'LFGauss', rates: [Rate.Audio, Rate.Control], defaults: [['duration', 1], ['width', 0.1], ['iphase', 0], ['loop', 1], ['action', 0]]});
registerUGen({name: 'LFNoise0', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 500]]});
registerUGen({name: 'LFNoise1', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 500]]});
registerUGen({name: 'LFNoise2', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 500]]});
registerUGen({name: 'LFPar', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 440], ['iphase', 0]]});
registerUGen({name: 'LFPulse', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 440], ['iphase', 0], ['width', 0.5]]});
registerUGen({name: 'LFSaw', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 440], ['iphase', 0]]});
registerUGen({name: 'LFTri', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 440], ['iphase', 0]]});
registerUGen({name: 'Limiter', rates: [Rate.Audio], defaults: [['in', undefined], ['level', 1], ['dur', 0.01]]});
registerUGen({name: 'LinCongC', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['a', 1.1], ['c', 0.13], ['m', 1], ['xi', 0]]});
registerUGen({name: 'LinCongL', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['a', 1.1], ['c', 0.13], ['m', 1], ['xi', 0]]});
registerUGen({name: 'LinCongN', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['a', 1.1], ['c', 0.13], ['m', 1], ['xi', 0]]});
registerUGen({name: 'Line', rates: [Rate.Audio, Rate.Control], defaults: [['start', 0], ['end', 1], ['dur', 1], ['action', 0]]});
registerUGen({name: 'Linen', rates: [Rate.Control], defaults: [['gate', 1], ['attackTime', 0.01], ['susLevel', 1], ['releaseTime', 1], ['action', 0]]});
registerUGen({name: 'LinExp', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['srclo', 0], ['srchi', 1], ['dstlo', 1], ['dsthi', 2]]});
registerUGen({name: 'LinPan2', rates: [Rate.Audio, Rate.Control], defaults: [['in', undefined], ['pos', 0], ['level', 1]], numOutputs: 2});
registerUGen({name: 'LinRand', rates: [Rate.Scalar], defaults: [['lo', 0], ['hi', 1], ['minmax', 0]]});
registerUGen({name: 'LinXFade2', rates: [Rate.Audio, Rate.Control], defaults: [['inA', undefined], ['inB', undefined], ['pan', 0], ['level', 1]]});
registerUGen({name: 'LocalBuf', rates: [Rate.Scalar], defaults: [['numChannels', 1], ['numFrames', undefined]]});
registerUGen({name: 'LocalIn', rates: [Rate.Audio, Rate.Control], defaults: [['numChannels', 1]]});
registerUGen({name: 'LocalOut', rates: [Rate.Audio, Rate.Control], defaults: [['channelsArray', undefined]], numOutputs: 0});
registerUGen({name: 'Logistic', rates: [Rate.Audio], defaults: [['chaosParam', 3], ['freq', 1000], ['init', 0.5]]});
registerUGen({name: 'LorenzL', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['s', 10], ['r', 28], ['b', 2.667], ['h', 0.05], ['xi', 0.1], ['yi', 0], ['zi', 0]]});
registerUGen({name: 'Loudness', rates: [Rate.Control], defaults: [['chain', undefined], ['smask', 0.25], ['tmask', 1]]});
registerUGen({name: 'LPF', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['freq', 440]]});
registerUGen({name: 'LPZ1', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0]]});
registerUGen({name: 'LPZ2', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0]]});
registerUGen({name: 'MantissaMask', rates: [Rate.Audio], defaults: [['in', 0], ['bits', 3]]});
registerUGen({name: 'MaxLocalBufs', rates: [Rate.Scalar], defaults: [['numLocalBufs', undefined]]});
registerUGen({name: 'Median', rates: [Rate.Audio, Rate.Control], defaults: [['length', 3], ['in', 0]]});
registerUGen({name: 'MFCC', rates: [Rate.Control], defaults: [['chain', undefined], ['numcoeff', 13]]});
registerUGen({name: 'MidEQ', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['freq', 440], ['rq', 1], ['db', 0]]});
registerUGen({name: 'MoogFF', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['freq', 100], ['gain', 2], ['reset', 0]]});
registerUGen({name: 'MostChange', rates: [Rate.Audio, Rate.Control], defaults: [['a', 0], ['b', 0]]});
registerUGen({name: 'MouseButton', rates: [Rate.Control], defaults: [['up', 0], ['down', 1], ['lag', 0.2]]});
registerUGen({name: 'MouseX', rates: [Rate.Control], defaults: [['min', 0], ['max', 1], ['warp', 0], ['lag', 0.2]]});
registerUGen({name: 'MouseY', rates: [Rate.Control], defaults: [['min', 0], ['max', 1], ['warp', 0], ['lag', 0.2]]});
registerUGen({name: 'Normalizer', rates: [Rate.Audio], defaults: [['in', undefined], ['level', 1], ['dur', 0.01]]});
registerUGen({name: 'NRand', rates: [Rate.Scalar], defaults: [['lo', 0], ['hi', 1], ['n', 0]]});
registerUGen({name: 'NumAudioBuses', rates: [Rate.Scalar], defaults: []});
registerUGen({name: 'NumBuffers', rates: [Rate.Scalar], defaults: []});
registerUGen({name: 'NumControlBuses', rates: [Rate.Scalar], defaults: []});
registerUGen({name: 'NumInputBuses', rates: [Rate.Scalar], defaults: []});
registerUGen({name: 'NumOutputBuses', rates: [Rate.Scalar], defaults: []});
registerUGen({name: 'NumRunningSynths', rates: [Rate.Scalar, Rate.Control], defaults: []});
registerUGen({name: 'OffsetOut', rates: [Rate.Audio], defaults: [['bus', undefined], ['channelsArray', undefined]], numOutputs: 0});
registerUGen({name: 'OnePole', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['coef', 0.5]]});
registerUGen({name: 'OneZero', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['coef', 0.5]]});
registerUGen({name: 'Onsets', rates: [Rate.Control], defaults: [['chain', undefined], ['threshold', 0.5], ['odftype', 3], ['relaxtime', 1], ['floor', 0.1], ['mingap', 10], ['medianspan', 11], ['whtype', 1], ['rawodf', 0]]});
registerUGen({name: 'Osc', rates: [Rate.Audio, Rate.Control], defaults: [['buffer', undefined], ['freq', 440], ['phase', 0]]});
registerUGen({name: 'Out', rates: [Rate.Audio, Rate.Control], defaults: [['bus', undefined], ['channelsArray', undefined]], numOutputs: 0});
registerUGen({name: 'Pan2', rates: [Rate.Audio, Rate.Control], defaults: [['in', undefined], ['pos', 0], ['level', 1]], numOutputs: 2});
registerUGen({name: 'Pan4', rates: [Rate.Audio, Rate.Control], defaults: [['in', undefined], ['xpos', 0], ['ypos', 0], ['level', 1]], numOutputs: 4});
registerUGen({name: 'PanAz', rates: [Rate.Audio, Rate.Control], defaults: [['numChannels', undefined], ['in', undefined], ['pos', 0], ['level', 1], ['width', 2], ['orientation', 0.5]]});
registerUGen({name: 'PanB', rates: [Rate.Audio, Rate.Control], defaults: [['in', undefined], ['azimuth', 0], ['elevation', 0], ['gain', 1]], numOutputs: 4});
registerUGen({name: 'PanB2', rates: [Rate.Audio, Rate.Control], defaults: [['in', undefined], ['azimuth', 0], ['gain', 1]], numOutputs: 3});
registerUGen({name: 'PartConv', rates: [Rate.Audio], defaults: [['in', undefined], ['fftsize', undefined], ['irbufnum', undefined]]});
registerUGen({name: 'Pause', rates: [Rate.Control], defaults: [['gate', undefined], ['id', undefined]], numOutputs: 0});
registerUGen({name: 'PauseSelf', rates: [Rate.Control], defaults: [['in', undefined]], numOutputs: 0});
registerUGen({name: 'PauseSelfWhenDone', rates: [Rate.Control], defaults: [['src', undefined]], numOutputs: 0});
registerUGen({name: 'Peak', rates: [Rate.Audio, Rate.Control], defaults: [['trig', 0], ['reset', 0]]});
registerUGen({name: 'PeakFollower', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['decay', 0.999]]});
registerUGen({name: 'Phasor', rates: [Rate.Audio, Rate.Control], defaults: [['trig', 0], ['rate', 1], ['start', 0], ['end', 1], ['resetPos', 0]]});
registerUGen({name: 'PinkNoise', rates: [Rate.Audio, Rate.Control], defaults: []});
registerUGen({name: 'Pitch', rates: [Rate.Control], defaults: [['in', undefined], ['initFreq', 440], ['minFreq', 60], ['maxFreq', 4000], ['execFreq', 100], ['maxBinsPerOctave', 16], ['median', 1], ['ampThreshold', 0.01], ['peakThreshold', 0.5], ['downSample', 1], ['clar', 0]], numOutputs: 2});
registerUGen({name: 'PitchShift', rates: [Rate.Audio], defaults: [['in', undefined], ['windowSize', 0.2], ['pitchRatio', 1], ['pitchDispersion', 0], ['timeDispersion', 0]]});
registerUGen({name: 'PlayBuf', rates: [Rate.Audio, Rate.Control], defaults: [['numChannels', undefined], ['bufnum', 0], ['rate', 1], ['trigger', 1], ['startPos', 0], ['loop', 0], ['action', 0]]});
registerUGen({name: 'Pluck', rates: [Rate.Audio], defaults: [['in', 0], ['trig', 1], ['maxdelaytime', 0.2], ['delaytime', 0.2], ['decaytime', 1], ['coef', 0.5]]});
registerUGen({name: 'Poll', rates: [Rate.Audio, Rate.Control], defaults: [['trig', 0], ['in', 0], ['label', undefined], ['trigId', -1]]});
registerUGen({name: 'PSinGrain', rates: [Rate.Audio], defaults: [['freq', 440], ['dur', 0.2], ['amp', 1]]});
registerUGen({name: 'Pulse', rates: [Rate.Audio], defaults: [['freq', 440], ['width', 0.5]]});
registerUGen({name: 'PulseCount', rates: [Rate.Audio, Rate.Control], defaults: [['trig', 0], ['reset', 0]]});
registerUGen({name: 'PulseDivider', rates: [Rate.Audio, Rate.Control], defaults: [['trig', 0], ['div', 2], ['startVal', 0]]});
registerUGen({name: 'PV_Add', rates: [Rate.Control], defaults: [['bufferA', undefined], ['bufferB', undefined]]});
registerUGen({name: 'PV_BinScramble', rates: [Rate.Control], defaults: [['buffer', undefined], ['wipe', 0], ['width', 0.2], ['trig', 0]]});
registerUGen({name: 'PV_BinShift', rates: [Rate.Control], defaults: [['buffer', undefined], ['stretch', 1], ['shift', 0]]});
registerUGen({name: 'PV_BinWipe', rates: [Rate.Control], defaults: [['bufferA', undefined], ['bufferB', undefined], ['wipe', 0]]});
registerUGen({name: 'PV_BrickWall', rates: [Rate.Control], defaults: [['buffer', undefined], ['wipe', 0]]});
registerUGen({name: 'PV_ConformalMap', rates: [Rate.Control], defaults: [['buffer', undefined], ['areal', 0], ['aimag', 0]]});
registerUGen({name: 'PV_Conj', rates: [Rate.Control], defaults: [['buffer', undefined]]});
registerUGen({name: 'PV_Copy', rates: [Rate.Control], defaults: [['bufferA', undefined], ['bufferB', undefined]]});
registerUGen({name: 'PV_CopyPhase', rates: [Rate.Control], defaults: [['bufferA', undefined], ['bufferB', undefined]]});
registerUGen({name: 'PV_Diffuser', rates: [Rate.Control], defaults: [['buffer', undefined], ['trig', 0]]});
registerUGen({name: 'PV_Div', rates: [Rate.Control], defaults: [['bufferA', undefined], ['bufferB', undefined]]});
registerUGen({name: 'PV_HainsworthFoote', rates: [Rate.Audio], defaults: [['buffer', undefined], ['proph', 0], ['propf', 0], ['threshold', 1], ['waitTime', 0.04]]});
registerUGen({name: 'PV_JensenAndersen', rates: [Rate.Audio], defaults: [['buffer', undefined], ['propsc', 0.25], ['prophfe', 0.25], ['prophfc', 0.25], ['propsf', 0.25], ['threshold', 1], ['waitTime', 0.04]]});
registerUGen({name: 'PV_LocalMax', rates: [Rate.Control], defaults: [['buffer', undefined], ['threshold', 0]]});
registerUGen({name: 'PV_MagAbove', rates: [Rate.Control], defaults: [['buffer', undefined], ['threshold', 0]]});
registerUGen({name: 'PV_MagBelow', rates: [Rate.Control], defaults: [['buffer', undefined], ['threshold', 0]]});
registerUGen({name: 'PV_MagClip', rates: [Rate.Control], defaults: [['buffer', undefined], ['threshold', 0]]});
registerUGen({name: 'PV_MagDiv', rates: [Rate.Control], defaults: [['bufferA', undefined], ['bufferB', undefined], ['zeroed', 0.0001]]});
registerUGen({name: 'PV_MagFreeze', rates: [Rate.Control], defaults: [['buffer', undefined], ['freeze', 0]]});
registerUGen({name: 'PV_MagMul', rates: [Rate.Control], defaults: [['bufferA', undefined], ['bufferB', undefined]]});
registerUGen({name: 'PV_MagNoise', rates: [Rate.Control], defaults: [['buffer', undefined]]});
registerUGen({name: 'PV_MagShift', rates: [Rate.Control], defaults: [['buffer', undefined], ['stretch', 1], ['shift', 0]]});
registerUGen({name: 'PV_MagSmear', rates: [Rate.Control], defaults: [['buffer', undefined], ['bins', 0]]});
registerUGen({name: 'PV_MagSquared', rates: [Rate.Control], defaults: [['buffer', undefined]]});
registerUGen({name: 'PV_Max', rates: [Rate.Control], defaults: [['bufferA', undefined], ['bufferB', undefined]]});
registerUGen({name: 'PV_Min', rates: [Rate.Control], defaults: [['bufferA', undefined], ['bufferB', undefined]]});
registerUGen({name: 'PV_Mul', rates: [Rate.Control], defaults: [['bufferA', undefined], ['bufferB', undefined]]});
registerUGen({name: 'PV_PhaseShift', rates: [Rate.Control], defaults: [['buffer', undefined], ['shift', undefined]]});
registerUGen({name: 'PV_PhaseShift270', rates: [Rate.Control], defaults: [['buffer', undefined]]});
registerUGen({name: 'PV_PhaseShift90', rates: [Rate.Control], defaults: [['buffer', undefined]]});
registerUGen({name: 'PV_RandComb', rates: [Rate.Control], defaults: [['buffer', undefined], ['wipe', 0], ['trig', 0]]});
registerUGen({name: 'PV_RandWipe', rates: [Rate.Control], defaults: [['bufferA', undefined], ['bufferB', undefined], ['wipe', 0], ['trig', 0]]});
registerUGen({name: 'PV_RectComb', rates: [Rate.Control], defaults: [['buffer', undefined], ['numTeeth', 0], ['phase', 0], ['width', 0.5]]});
registerUGen({name: 'PV_RectComb2', rates: [Rate.Control], defaults: [['bufferA', undefined], ['bufferB', undefined], ['numTeeth', 0], ['phase', 0], ['width', 0.5]]});
registerUGen({name: 'QuadC', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['a', 1], ['b', -1], ['c', -0.75], ['xi', 0]]});
registerUGen({name: 'QuadL', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['a', 1], ['b', -1], ['c', -0.75], ['xi', 0]]});
registerUGen({name: 'QuadN', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['a', 1], ['b', -1], ['c', -0.75], ['xi', 0]]});
registerUGen({name: 'RadiansPerSample', rates: [Rate.Scalar], defaults: []});
registerUGen({name: 'Ramp', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['lagTime', 0.1]]});
registerUGen({name: 'Rand', rates: [Rate.Scalar], defaults: [['lo', 0], ['hi', 1]]});
registerUGen({name: 'RandID', rates: [Rate.Scalar, Rate.Control], defaults: [['seed', 0]], numOutputs: 0});
registerUGen({name: 'RandSeed', rates: [Rate.Scalar, Rate.Control], defaults: [['trig', 0], ['seed', 56789]], numOutputs: 0});
registerUGen({name: 'RecordBuf', rates: [Rate.Audio, Rate.Control], defaults: [['inputArray', undefined], ['bufnum', 0], ['offset', 0], ['recLevel', 1], ['preLevel', 0], ['run', 1], ['loop', 1], ['trigger', 1], ['action', 0]], numOutputs: 0});
registerUGen({name: 'ReplaceOut', rates: [Rate.Audio, Rate.Control], defaults: [['bus', undefined], ['channelsArray', undefined]], numOutputs: 0});
registerUGen({name: 'Resonz', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['freq', 440], ['bwr', 1]]});
registerUGen({name: 'RHPF', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['freq', 440], ['rq', 1]]});
registerUGen({name: 'Ringz', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['freq', 440], ['decayTime', 1]]});
registerUGen({name: 'RLPF', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['freq', 440], ['rq', 1]]});
registerUGen({name: 'Rotate2', rates: [Rate.Audio, Rate.Control], defaults: [['x', undefined], ['y', undefined], ['pos', 0]], numOutputs: 2});
registerUGen({name: 'RunningMax', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['trig', 0]]});
registerUGen({name: 'RunningMin', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['trig', 0]]});
registerUGen({name: 'RunningSum', rates: [Rate.Audio, Rate.Control], defaults: [['in', undefined], ['numsamp', 40]]});
registerUGen({name: 'SampleDur', rates: [Rate.Scalar], defaults: []});
registerUGen({name: 'SampleRate', rates: [Rate.Scalar], defaults: []});
registerUGen({name: 'Saw', rates: [Rate.Audio], defaults: [['freq', 440]]});
registerUGen({name: 'Schmidt', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['lo', 0], ['hi', 1]]});
registerUGen({name: 'ScopeOut', rates: [Rate.Audio], defaults: [['inputArray', undefined], ['bufnum', 0]], numOutputs: 0});
registerUGen({name: 'ScopeOut2', rates: [Rate.Audio, Rate.Control], defaults: [['inputArray', undefined], ['scopeNum', 0], ['maxFrames', 4096], ['scopeFrames', 4096]], numOutputs: 0});
registerUGen({name: 'Select', rates: [Rate.Audio, Rate.Control], defaults: [['which', undefined], ['channelsArray', undefined]]});
registerUGen({name: 'SendReply', rates: [Rate.Audio, Rate.Control], defaults: [['trig', 0], ['cmdName', undefined], ['values', 0], ['replyId', -1]], numOutputs: 0});
registerUGen({name: 'SendTrig', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['id', 0], ['value', 0]], numOutputs: 0});
registerUGen({name: 'SetBuf', rates: [Rate.Audio, Rate.Control], defaults: [['buf', undefined], ['values', undefined], ['offset', 0]], numOutputs: 0});
registerUGen({name: 'SetResetFF', rates: [Rate.Audio, Rate.Control], defaults: [['trig', 0], ['reset', 0]]});
registerUGen({name: 'Shaper', rates: [Rate.Control, Rate.Scalar], defaults: [['bufnum', undefined], ['in', 0]]});
registerUGen({name: 'SharedIn', rates: [Rate.Control], defaults: [['bus', 0], ['numChannels', 1]]});
registerUGen({name: 'SharedOut', rates: [Rate.Control], defaults: [['bus', undefined], ['channelsArray', undefined]]});
registerUGen({name: 'Silent', rates: [Rate.Audio], defaults: [['numChannels', 1]]});
registerUGen({name: 'SinOsc', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 440], ['phase', 0]]});
registerUGen({name: 'SinOscFB', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 440], ['feedback', 0]]});
registerUGen({name: 'Slew', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['up', 1], ['dn', 1]]});
registerUGen({name: 'Slope', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0]]});
registerUGen({name: 'SOS', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['a0', 0], ['a1', 0], ['a2', 0], ['b1', 0], ['b2', 0]]});
registerUGen({name: 'SpecCentroid', rates: [Rate.Control], defaults: [['chain', undefined]]});
registerUGen({name: 'SpecFlatness', rates: [Rate.Control], defaults: [['chain', undefined]]});
registerUGen({name: 'SpecPcile', rates: [Rate.Control], defaults: [['chain', undefined], ['fraction', 0.5], ['interpolate', 0]]});
registerUGen({name: 'Spring', rates: [Rate.Audio], defaults: [['in', 0], ['spring', 0], ['damp', 0]]});
registerUGen({name: 'StandardL', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['k', 1], ['xi', 0.5], ['yi', 0]]});
registerUGen({name: 'StandardN', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 22050], ['k', 1], ['xi', 0.5], ['yi', 0]]});
registerUGen({name: 'Stepper', rates: [Rate.Audio, Rate.Control], defaults: [['trig', 0], ['reset', 0], ['min', 0], ['max', 7], ['step', 1], ['resetval', 1]]});
registerUGen({name: 'StereoConvolution2L', rates: [Rate.Audio], defaults: [['in', undefined], ['kernelL', undefined], ['kernelR', undefined], ['trigger', undefined], ['framesize', 512], ['crossfade', 1]], numOutputs: 2});
registerUGen({name: 'SubsampleOffset', rates: [Rate.Scalar], defaults: []});
registerUGen({name: 'Sweep', rates: [Rate.Audio, Rate.Control], defaults: [['trig', 0], ['rate', 1]]});
registerUGen({name: 'SyncSaw', rates: [Rate.Audio, Rate.Control], defaults: [['syncFreq', 440], ['sawFreq', 440]]});
registerUGen({name: 'T2A', rates: [Rate.Audio], defaults: [['in', 0], ['offset', 0]]});
registerUGen({name: 'T2K', rates: [Rate.Control], defaults: [['in', 0]]});
registerUGen({name: 'TBall', rates: [Rate.Audio], defaults: [['in', 0], ['g', 10], ['damp', 0], ['friction', 0.01]]});
registerUGen({name: 'TDelay', rates: [Rate.Audio, Rate.Control], defaults: [['trig', 0], ['dur', 0.1]]});
registerUGen({name: 'TDuty', rates: [Rate.Audio, Rate.Control], defaults: [['dur', 1], ['reset', 0], ['action', 0], ['level', 1], ['gapFirst', 0]]});
registerUGen({name: 'TExpRand', rates: [Rate.Audio, Rate.Control], defaults: [['lo', 0.01], ['hi', 1], ['trig', 0]]});
registerUGen({name: 'TGrains', rates: [Rate.Audio], defaults: [['numChannels', 2], ['trigger', 0], ['bufnum', 0], ['rate', 1], ['centerPos', 0], ['dur', 0.1], ['pan', 0], ['amp', 0.1], ['interp', 4]]});
registerUGen({name: 'Timer', rates: [Rate.Audio, Rate.Control], defaults: [['trig', 0]]});
registerUGen({name: 'TIRand', rates: [Rate.Control, Rate.Audio], defaults: [['lo', 0], ['hi', 127], ['trig', 0]]});
registerUGen({name: 'ToggleFF', rates: [Rate.Audio, Rate.Control], defaults: [['trig', 0]]});
registerUGen({name: 'TRand', rates: [Rate.Control, Rate.Audio], defaults: [['lo', 0], ['hi', 1], ['trig', 0]]});
registerUGen({name: 'Trapezoid', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['a', 0.2], ['b', 0.4], ['c', 0.6], ['d', 0.8]]});
registerUGen({name: 'Trig', rates: [Rate.Audio, Rate.Control], defaults: [['trig', 0], ['dur', 0.1]]});
registerUGen({name: 'Trig1', rates: [Rate.Audio, Rate.Control], defaults: [['trig', 0], ['dur', 0.1]]});
registerUGen({name: 'TWindex', rates: [Rate.Audio, Rate.Control], defaults: [['trig', undefined], ['channelsArray', undefined], ['normalize', 0]]});
registerUGen({name: 'TwoPole', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['freq', 440], ['radius', 0.8]]});
registerUGen({name: 'TwoZero', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['freq', 440], ['radius', 0.8]]});
registerUGen({name: 'VarSaw', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 440], ['iphase', 0], ['width', 0.5]]});
registerUGen({name: 'VDiskIn', rates: [Rate.Audio], defaults: [['numChannels', undefined], ['bufnum', undefined], ['rate', 1], ['loop', 0], ['sendID', 0]]});
registerUGen({name: 'Vibrato', rates: [Rate.Audio, Rate.Control], defaults: [['freq', 440], ['rate', 6], ['depth', 0.02], ['delay', 0], ['onset', 0], ['rateVariation', 0.04], ['depthVariation', 0.1], ['iphase', 0]]});
registerUGen({name: 'VOsc', rates: [Rate.Audio, Rate.Control], defaults: [['bufpos', undefined], ['freq', 440], ['phase', 0]]});
registerUGen({name: 'VOsc3', rates: [Rate.Audio, Rate.Control], defaults: [['bufpos', undefined], ['freq1', 110], ['freq2', 220], ['freq3', 440]]});
registerUGen({name: 'Warp1', rates: [Rate.Audio], defaults: [['numChannels', 1], ['bufnum', 0], ['pointer', 0], ['freqScale', 1], ['windowSize', 0.1], ['envbufnum', -1], ['overlaps', 8], ['windowRandRatio', 0], ['interp', 1]]});
registerUGen({name: 'WhiteNoise', rates: [Rate.Audio, Rate.Control], defaults: []});
registerUGen({name: 'Wrap', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0], ['lo', 0], ['hi', 1]]});
registerUGen({name: 'WrapIndex', rates: [Rate.Control, Rate.Scalar], defaults: [['bufnum', undefined], ['in', 0]]});
registerUGen({name: 'XFade2', rates: [Rate.Audio, Rate.Control], defaults: [['inA', undefined], ['inB', undefined], ['pan', 0], ['level', 1]]});
registerUGen({name: 'XLine', rates: [Rate.Audio, Rate.Control], defaults: [['start', 1], ['end', 2], ['dur', 1], ['action', 0]]});
registerUGen({name: 'XOut', rates: [Rate.Audio, Rate.Control], defaults: [['bus', undefined], ['xfade', undefined], ['channelsArray', undefined]], numOutputs: 0});
registerUGen({name: 'ZeroCrossing', rates: [Rate.Audio, Rate.Control], defaults: [['in', 0]]});

// Operator UGens (special-cased in the compiler, not from Overtone)
registerUGen({name: 'BinaryOpUGen', rates: [Rate.Audio, Rate.Control, Rate.Scalar], defaults: [['a', undefined], ['b', undefined]]});
registerUGen({name: 'UnaryOpUGen', rates: [Rate.Audio, Rate.Control, Rate.Scalar], defaults: [['a', undefined]]});
registerUGen({name: 'MulAdd', rates: [Rate.Audio, Rate.Control, Rate.Scalar], defaults: [['in', undefined], ['mul', 1], ['add', 0]]});
