export const ELEMENTS = {
  SC_DISPLAY: 'sc-display',
  SC_IF: 'sc-if',
  SC_RANGE: 'sc-range',
  SC_CHECKBOX: 'sc-checkbox',
  SC_GROUP: 'sc-group',
  SC_SYNTH: 'sc-synth',
  SC_RUN: 'sc-run',
  SC_PLUGIN: 'sc-plugin',
  SC_SYNTHDEF: 'sc-synthdef',
  SC_UGEN: 'sc-ugen',
  SC_CONTROL: 'sc-control',
  SC_VAR: 'sc-var',
  SC_SELECT: 'sc-select',
  SC_OPTION: 'sc-option',
  SC_RADIO_GROUP: 'sc-radio-group',
  SC_RADIO: 'sc-radio',
} as const;
