import {ELEMENTS} from '@/constants/sc-elements.ts';
import {ScDisplay} from './sc-display.ts';
import {ScIf} from './sc-if.ts';
import {ScKnob} from './sc-knob.ts';
import {ScRange} from './sc-range.ts';
import {ScSlider} from './sc-slider.ts';
import {ScSwitch} from './sc-switch.ts';
import {ScGroup} from './sc-group.ts';
import {ScSynth} from './sc-synth.ts';
import {ScToggle} from './sc-toggle.ts';

customElements.define(ELEMENTS.SC_DISPLAY, ScDisplay);
customElements.define(ELEMENTS.SC_IF, ScIf);
customElements.define(ELEMENTS.SC_KNOB, ScKnob);
customElements.define(ELEMENTS.SC_RANGE, ScRange);
customElements.define(ELEMENTS.SC_SLIDER, ScSlider);
customElements.define(ELEMENTS.SC_SWITCH, ScSwitch);
customElements.define(ELEMENTS.SC_GROUP, ScGroup);
customElements.define(ELEMENTS.SC_SYNTH, ScSynth);
customElements.define(ELEMENTS.SC_TOGGLE, ScToggle);
