#!/usr/bin/env bash
# Wipe everything generated by setup + build, so the project can be
# rebuilt from a clean slate. Removes:
#
#   superdirt-deps/        # everything yarn superdirt-setup downloaded
#   dist/                  # Vite production build output
#   src-tauri/target/      # Rust build output (Cargo)
#
# Does NOT touch node_modules/ (managed by yarn) or any committed
# source. Idempotent and safe to rerun.
#
# Wire: `yarn cleanup`. After it, run `yarn superdirt-setup` to refetch
# the runtime deps, then the regular workflow continues.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
skip() { printf '  \033[33m·\033[0m %s\n' "$*"; }

remove_if_present() {
  local path="$1"
  if [ -e "$path" ]; then
    rm -rf "$path"
    ok "removed $path"
  else
    skip "$path not present"
  fi
}

echo "cleaning generated artifacts in $REPO_ROOT"
echo

remove_if_present "$REPO_ROOT/superdirt-deps"
remove_if_present "$REPO_ROOT/dist"
remove_if_present "$REPO_ROOT/src-tauri/target"

echo
echo "done. To rebuild from scratch:"
echo "  yarn superdirt-setup   # refetch runtime deps"
echo "  yarn build             # rebuild frontend"
echo "  yarn tauri build       # rebuild native app (slow)"
